# Schema for the configuration files of the Sitemap module.
sitemap.settings:
  type: config_object
  label: 'Sitemap settings'
  mapping:
    page_title:
      type: label
      label: 'Page title'
    message:
      type: text_format
      label: 'Sitemap message'
    show_front:
      type: boolean
      label: 'Show front flag'
    show_titles:
      type: boolean
      label: 'Show titles flag'
    show_books:
      type: sequence
      label: 'Books to display'
      sequence:
        - type: integer
          label: 'Book id'
    books_expanded:
      type: boolean
      label: 'Books expanded flag'
    show_menus:
      type: sequence
      label: 'Menus to display'
      sequence:
        - type: string
          label: 'Menu id'
    show_menus_hidden:
      type: boolean
      label: 'Show disabled menu items flag'
    show_vocabularies:
      type: sequence
      label: 'Vocabularies to display'
      sequence:
        - type: string
          label: 'Vocabulary id'
    show_description:
      type: boolean
      label: 'Show vocabulary description flag'
    show_count:
      type: boolean
      label: 'Show node count by taxonomy term flag'
    vocabulary_show_links:
      type: boolean
      label: "Show links for taxonomy terms even if they don't contain any nodes"
    vocabulary_depth:
      type: integer
      label: 'Vocabulary depth'
    term_threshold:
      type: integer
      label: 'Term count threshold'
    forum_threshold:
      type: integer
      label: 'Forum count threshold'
    rss_front:
      type: label
      label: 'RSS front'
    show_rss_links:
      type: integer
      label: 'Position of RSS links'
    rss_taxonomy:
      type: integer
      label: 'RSS depth'
    css:
      type: boolean
      label: 'Include css file flag'
    order:
      type: sequence
      label: 'Sitemap order'
      sequence:
        - type: sitemap.order.[%key]

sitemap.order.*:
  type: integer
  label: 'Weight'

system.menu.*.third_party.sitemap:
  type: mapping
  label: 'Menu customizations'
  mapping:
    sitemap_display_name:
      type: text
      label: 'Sitemap display name'